repos:
  # Next hooks are Code Quality hooks. 
  # If you want them to run on each commit, uncomment them
  # These are OPTIONAL.
   #- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
   #  rev: v2.3.0
   #  hooks:
   #    - id: pretty-format-golang
   #      args:
   #        - --autofix
   - repo: https://github.com/golangci/golangci-lint
     rev: v1.44.2
     hooks:
       - id: golangci-lint
         entry: echo "hello"
